### ISSUE TITLE
Unable to detrend with dask and tcp cluster

### ISSUE THREAD

**Issue by oarcher** [umr-lops/xsarsea#36]
When using dask on a tcp cluster, detrend fail:

```python
import xsar
import xsarsea
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(protocol='tcp://') # works without tcp
client = Client(cluster)
ds_L1 = xsar.open_dataset('/S1A_IW_GRDH_1SDV_20210710T054447_20210710T054512_038711_04916F_5179.SAFE', resolution = '200m')
ds_L1['sigma0_detrend'] = xsarsea.sigma0_detrend(ds_L1['sigma0'], ds_L1['incidence'])
```

```
[...]
File ~/anaconda3/envs/xsar/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py:633, in CloudPickler.dump(self, obj)
    631 def dump(self, obj):
    632     try:
--> 633         return Pickler.dump(self, obj)
    634     except RuntimeError as e:
    635         if "recursion" in e.args[0]:

PicklingError: Can't pickle <ufunc 'gmf_cmodifr2'>: attribute lookup gmf_cmodifr2 on __main__ failed
```

That's because `gmf_cmodifr2` is not picklable, because it's not defined in `__main__` (ie **top level**). 
From https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled:

> functions (built-in and user-defined) accessible from the **top level** of a module (using def, not lambda);

**Comment by oarcher** [comment]
Minimal example that show that `gmf_cmodifr2` is not picklable:

```python
import pickle
from xsarsea.windspeed.gmfs_impl import gmf_cmodifr2
pickle.loads(pickle.dumps(gmf_cmodifr2))

Traceback (most recent call last):
  File "/snap/pycharm-professional/285/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/285/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/oarcher/Develop/xsartesting/dask_detend.py", line 8, in <module>
    pickle.loads(pickle.dumps(gmf_cmodifr2))
_pickle.PicklingError: Can't pickle <function gmf_cmodifr2 at 0x7f46c8198790>: it's not the same object as xsarsea.windspeed.gmfs_impl.gmf_cmodifr2
python-BaseException
```
